"""
Django settings for monblogprojet project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os # Assurez-vous que os est importé en haut du fichier

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@&=6n5@b^os3ktl8kh^*mq)v-fr%5e1u%-2bm2+&^rg1n0=00e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True  # IMPÉRATIF en production

ALLOWED_HOSTS = ["productionblogapp-production-2fbd.up.railway.app","127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'blogapp.apps.BlogappConfig', # Ou juste 'blogapp'
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'monblogprojet.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(os.path.dirname(__file__), '..', 'templates')],
        'APP_DIRS': True, # Laisse Django chercher aussi les templates dans les dossiers 'templates' de chaque app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'monblogprojet.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "Whitenoise.storage.CompressedManifestStaticFilesStorage"
MEDIA_URL = "media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'  # Redirige vers la page d'accueil (racine) après connexion
LOGOUT_REDIRECT_URL = '/'  # Optionnel : Redirige vers l'accueil après déconnexion (déjà géré par notre vue)

# Note: LOGIN_REDIRECT_URL indique à Django où aller après une connexion réussie si le
# décorateur `@login_required` a intercepté l'utilisateur. Notre vue `connexion_view` redirige déjà
# vers `blogapp:accueil`, donc ceci est surtout pour le comportement par défaut de `@login_required`.

# Optionnel mais bonne pratique pour le développement :
# STATICFILES_DIRS = [
# os.path.join(BASE_DIR, 'static'), # Pour un dossier static global au projet
# ]
# Pour notre cas, Django trouvera les fichiers statiques dans chaque application
# grâce à 'django.contrib.staticfiles' dans INSTALLED_APPS et APP_DIRS=True dans TEMPLATES.